### ISSUE TITLE
PrestoFileSystemCache have not take LocalFileSystem into consideration

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino-hadoop-apache#24]
The same issue is described and discussed in prestodb here https://github.com/prestodb/presto/issues/14642

PrestoFileSystemCache wraps all the file systems with `PrestoFileSystemCache$FileSystemWrapper` which extends `FilterFileSystem`. Any attempt to create LocalFileSystem causes exception: `java.lang.ClassCastException: class org.apache.hadoop.fs.PrestoFileSystemCache$FileSystemWrapper cannot be cast to class org.apache.hadoop.fs.LocalFileSystem`

As an example `S3AFileSystem` uses local file system to store blocks before uploading them to S3.
```
java.lang.ClassCastException: class org.apache.hadoop.fs.PrestoFileSystemCache$FileSystemWrapper cannot be cast to class org.apache.hadoop.fs.LocalFileSystem (org.apache.hadoop.fs.PrestoFileSystemCache$FileSystemWrapper and org.apache.hadoop.fs.LocalFileSystem are in unnamed module of loader io.prestosql.server.PluginClassLoader @4f1037ca)
	at org.apache.hadoop.fs.FileSystem.getLocal(FileSystem.java:435)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.confChanged(LocalDirAllocator.java:317)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.getLocalPathForWrite(LocalDirAllocator.java:394)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.createTmpFileForWrite(LocalDirAllocator.java:477)
	at org.apache.hadoop.fs.LocalDirAllocator.createTmpFileForWrite(LocalDirAllocator.java:213)
	at org.apache.hadoop.fs.s3a. S3AFileSystem.createTmpFileForWrite(S3AFileSystem.java:664)
	at org.apache.hadoop.fs.s3a.S3ADataBlocks$DiskBlockFactory.create(S3ADataBlocks.java:811)
	at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.createBlockIfNeeded(S3ABlockOutputStream.java:190)
	at org.apache.hadoop.fs.s3a.S3ABlockOutputStream.<init>(S3ABlockOutputStream.java:168)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.create(S3AFileSystem.java:866)
```

**Comment by findepi** [comment]
What is your use case to use  `S3AFileSystem` with Presto?

**Comment by davseitsev** [comment]
We use `S3AFileSystem` with presto-hive plugin and our own plugins with `S3Guard` to mitigate eventual consistency problems.

**Comment by findepi** [comment]
I am disabling issues in this repository, whcih is really just a "helper" for https://github.com/trinodb/trino, so that discussions and problems remain visible to all potential participants.
If you're still having this problem, please file an issue at https://github.com/trinodb/trino
